### ISSUE TITLE
it seems laravel-remember-all doesn't support laravel 6

### ISSUE THREAD

**Issue by ghost** [barchart/laravel-remember-all#2]
when I try to install laravel-remember-all via composer, I get this error:
  Problem 1
    - Installation request for barchart/laravel-remember-all ^0.1.2 -> satisfiable by barchart/laravel-remember-all[v0.1.2].
    - Conclusion: remove laravel/framework v6.0.3
    - Conclusion: don't install laravel/framework v6.0.3
    - barchart/laravel-remember-all v0.1.2 requires illuminate/auth ~5.7 -> satisfiable by illuminate/auth[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].

**Comment by ManojKiranA** [comment]
yes . I think the package is not maintained.

**Comment by tomsisk** [comment]
You can open a pull request or I will get to this later this week.

**Comment by tomsisk** [comment]
Use `v1.0.0`
